name: build_for_debian

on: 
  workflow_dispatch:
   

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  # This workflow contains a single job called "greet"
  greet: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: build with docker 
        run: | 
          docker run \
            -u root:root \
            -e BOARD \
            -e BRANCH_BUILD=main\
            -e USE_BRANCH=BrailleRAP \
            -v $(pwd)/dist/:/home/builduser/dist \
            sgngodin/buildaccessbraillerap:latest
